/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::pa_linux_alsa::*;


#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_InitializeStreamInfo(
    info: *mut PaAlsaStreamInfo
)
{
    PaAlsa_InitializeStreamInfo(
        info
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_EnableRealtimeScheduling(
    s: *mut PaStream,
    enable: c_int
)
{
    PaAlsa_EnableRealtimeScheduling(
        s,
        enable
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_GetStreamInputCard(
    s: *mut PaStream,
    card: *mut c_int
) -> PaError
{
    PaAlsa_GetStreamInputCard(
        s,
        card
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_GetStreamOutputCard(
    s: *mut PaStream,
    card: *mut c_int
) -> PaError
{
    PaAlsa_GetStreamOutputCard(
        s,
        card
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_SetNumPeriods(
    numPeriods: c_int
) -> PaError
{
    PaAlsa_SetNumPeriods(
        numPeriods
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_SetRetriesBusy(
    retries: c_int
) -> PaError
{
    PaAlsa_SetRetriesBusy(
        retries
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaAlsa_SetLibraryPathName(
    pathName: *const c_char
)
{
    PaAlsa_SetLibraryPathName(
        pathName
    )
}

    