/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::pa_linux_pulseaudio::*;


#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaPulseAudio_RenameSource(
    s: *mut PaStream,
    streamName: *const c_char
) -> PaError
{
    PaPulseAudio_RenameSource(
        s,
        streamName
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PaPulseAudio_RenameSink(
    s: *mut PaStream,
    streamName: *const c_char
) -> PaError
{
    PaPulseAudio_RenameSink(
        s,
        streamName
    )
}

    