using PortAudioCSharp.AutoGenerated;
using PortAudioCSharp.Utils;

namespace PortAudioCSharp.Wrapper;

public class DeviceInfo
{
    public int StructVersion { get; }
    public string Name { get; }
    public int HostApi { get; }

    public int MaxInputChannels { get; }
    public int MaxOutputChannels { get; }
    public double DefaultLowInputLatency { get; }
    public double DefaultLowOutputLatency { get; }
    public double DefaultHighInputLatency { get; }
    public double DefaultHighOutputLatency { get; }
    public double DefaultSampleRate { get; }

    internal unsafe DeviceInfo(PaDeviceInfo* paDeviceInfo)
    {
        StructVersion = paDeviceInfo->structVersion;
        Name = Helper.ConvertText(paDeviceInfo->name);
        HostApi = paDeviceInfo->hostApi;
        MaxInputChannels = paDeviceInfo->maxInputChannels;
        MaxOutputChannels = paDeviceInfo->maxOutputChannels;
        DefaultLowInputLatency = paDeviceInfo->defaultLowInputLatency;
        DefaultLowOutputLatency = paDeviceInfo->defaultLowOutputLatency;
        DefaultHighInputLatency = paDeviceInfo->defaultHighInputLatency;
        DefaultHighOutputLatency = paDeviceInfo->defaultHighOutputLatency;
        DefaultSampleRate = paDeviceInfo->defaultSampleRate;
    }
}