using System;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Runtime.InteropServices;
using System.Threading;
using PortAudioCSharp.AutoGenerated;
using PortAudioCSharp.Exceptions;

[assembly: InternalsVisibleTo("PortAudioCSharp")]
namespace PortAudioCSharp.Wrapper;

internal unsafe class PortAudioOutStrem
{
    private readonly CancellationTokenSource cancellationTokenSource = new();
    private bool _isInitialized = false;
    private readonly void* _stream = NativeMemory.AllocZeroed((nuint)sizeof(void*));
    private readonly int _deviceIndex;
    private PaStreamParameters _outputParameter;
    private readonly double _sampleRate;
    private readonly PaStreamFlags _streamFlag;

    public PortAudioOutStrem(int deviceIndex, PaStreamParameters outputPatameter, double sampleRate, PaStreamFlags streamFlags)
    {
        _deviceIndex = deviceIndex;
        _outputParameter = outputPatameter;
        _sampleRate = sampleRate;
        _streamFlag = streamFlags;
        Initialize();
    }

    private void Initialize()
    {
        fixed (PaStreamParameters* pOutputParameter = &_outputParameter)
        {
            PortAudioException.ThrowIfError(NativeMethods.Pa_IsFormatSupported((PaStreamParameters*)nint.Zero, pOutputParameter, _sampleRate));
            fixed (void** pStream = &_stream)
            {
                PortAudioException.ThrowIfError(NativeMethods.Pa_OpenStream(pStream, (PaStreamParameters*)nint.Zero, pOutputParameter, _sampleRate, new CULong(NativeConsts.paFramesPerBufferUnspecified), new CULong((uint)_streamFlag), &StreamCallBack, (void*)nint.Zero));
            }
        }
        _isInitialized = true;
    }

    public void Dispose()
    {
        if (_isInitialized)
        {
            NativeMethods.Pa_CloseStream(_stream);
        }
        NativeMemory.Free(_stream);
    }

    [UnmanagedCallersOnly(CallConvs = [typeof(CallConvCdecl)])]
    private static int StreamCallBack(void* input, void* output, CULong frameCount, PaStreamCallbackTimeInfo* timeInfo, CULong statusFlag, void* userData) => (int)PaStreamCallbackResult.paComplete;
}
