using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text.Unicode;
using PortAudio.AutoGenerated;


namespace PortAudio.Wrapper;

public static unsafe class PortAudioWrapper
{
    public static unsafe string GetVersionText(){
        var verText = NativeMethods.Pa_GetVersionText();
        int count=0;
        while(*(verText+count)!='\0'){count++;}
        var text = string.Create(count,"",(Span<char> chars, string state)=>{
            Utf8.ToUtf16(new ReadOnlySpan<byte>(verText,count),chars,out _,out _);
        });
        return text;
    }
}
