using PortAudio.AutoGenerated;
using PortAudio.Exceptions;
using PortAudio.Wrapper;

namespace PortAudioCSharp;

public class PortAudioOutDevice : IDisposable
{
    private bool _isDisposed = true;
    public PortAudioOutDevice()
    {
        PortAudioException.ThrowIfError(PortAudioWrapper.Initialize());
        var defaultapi = PortAudioWrapper.GetDefaultHostApi();
        if(defaultapi < 0 ){
            PortAudioException.Throw((PaErrorCode)defaultapi);
        }
        _isDisposed = false;
    }

    public void Dispose()
    {
        if (!_isDisposed)
        {
            PortAudioException.ThrowIfError(PortAudioWrapper.Terminate());
        }
        _isDisposed = true;
    }
}