using PortAudioCSharp.AutoGenerated;
using PortAudioCSharp.Wrapper;
using System.Reflection;
using System.Runtime.InteropServices;
using PortAudioCSharp.Services;
using PortAudioCSharp.Devices;

NativeLibrary.SetDllImportResolver(typeof(NativeConsts).Assembly, DllImportResolver);
Console.WriteLine(PortAudioWrapper.GetVersionText());

using var service = new PortAudioService();

var hostApi = service.DefaultHostApi;
Console.WriteLine(hostApi.Name);

foreach (var h in service.GetAllHostApi())
{
    Console.WriteLine($"{h.Name}: Device {h.DeviceCount}");

    Console.WriteLine(h.DefaultInputDevice != null ? h.DefaultInputDevice.Name : "None");
    Console.WriteLine(h.DefaultOutputDevice != null ? h.DefaultOutputDevice.Name : "None");

    Console.WriteLine($"{h.Name}のデバイス一覧");
    foreach (var device in h.GetAllDevice())
    {
        Console.WriteLine(device.Name);
    }
}
Console.WriteLine("すべてのデバイス");
foreach(var d in service.GetAllDevice()){
    Console.WriteLine($"{d.Name}: HostApi {d.HostApi.Name}");
}

static IntPtr DllImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
{
    if (libraryName == "portaudio")
    {
        string path = "";
        string modifier = "lib";
        string extention = "";
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
        {
            path += "/usr/lib";
            extention = ".so.2";
        }

        if (RuntimeInformation.ProcessArchitecture == Architecture.X86 || RuntimeInformation.ProcessArchitecture == Architecture.X64)
        {
            path += "/x86_64-linux-gnu";
        }

        return NativeLibrary.Load(Path.Combine(path, $"{modifier}portaudio{extention}"), assembly, searchPath);
    }

    // Otherwise, fallback to default import resolver.
    return IntPtr.Zero;
}
